name: Release new extension build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Add node_modules/.bin to PATH
        run: echo "./node_modules/.bin" >> $GITHUB_PATH
      - name: Build WebExtension
        run: web-ext build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: web-ext-artifacts/github_webextension-*.zip
